name: POC-Project

services:
  minio-bronze:
    image: minio/minio
    container_name: minio-bronze
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # You access API at localhost:9000
      - "9001:9001"  # You access console at localhost:9001
    networks:
      - backend
    volumes:
      - bronze-minio-data:/data # if you don't add volumes at the bottom it is a bind voume
    
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  minio-gold:
    image: minio/minio
    container_name: minio-gold
    command: server /data --console-address ":9001"
    ports:
      - "9010:9000"  # You access API at localhost:9000
      - "9011:9001"  # You access console at localhost:9001
    networks:
      - backend
    volumes:
      - gold-minio-data:/data # if you don't add volumes at the bottom it is a bind voume
    
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  python-app:
    build: ./python-app
    container_name: python-app
    env_file:
      - .env
    depends_on:
      minio-bronze:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./python-app/Download:/app/Download
      - ./python-app/Upload:/app/Upload


networks:
  backend:

volumes:
  bronze-minio-data:  # now it it is named volume managed by docker
  gold-minio-data: